// <copyright file="OpenAIRole.cs" company="854 Things (tm)">
// Copyright (c) 854 Things (tm). All rights reserved.
// </copyright>

namespace OpenAIApiClient.Enums
{
    /// <summary>
    /// List of OpenAI roles for AI chat messages.
    /// </summary>
    public enum OpenAIRole
    {
        /// <summary>
        /// Sets the overall behavior, tone, or rules for the assistant.
        /// For Chat and Messages API
        /// </summary>
        System,

        /// <summary>
        /// Represents input from the human interacting with the model.
        /// For Chat and Messages API
        /// </summary>
        User,

        /// <summary>
        /// Represents responses generated by the AI assistant itself.
        /// For Chat and Messages API
        /// </summary>
        Assistant,

        /// <summary>
        /// (optional) → Used when the assistant calls a function/tool and provides its output back into the conversation.
        /// For Chat and Messages API
        /// </summary>
        Tool,

        /// <summary>
        /// A new role that lets developers insert special instructions or metadata into the conversation (e.g., controlling flow or injecting hidden context).
        /// i.e. more control over conversation flow
        /// e.g. "Always explain concepts with a real-world analogy."
        /// For Messages API only!
        /// </summary>
        Developer,
    }
}
